### ISSUE TITLE
Show Grid button shows off when grid is on

### ISSUE THREAD

**Issue by homerofgods** [Soldat/polyworks#4]
When you open PW, the button will always show the grid as OFF, even if it's ON.

See image: http://i.imgur.com/QBPWLuO.png

The Grid itself does what it supposed to, remembering my choice after closing. 
It's the button that tells me the grid is off when it's clearly not.

**Comment by ExHunter** [comment]
Cannot reproduce on win10 64 bit pro (maybe something else fixed it). 
![showgrid](https://cloud.githubusercontent.com/assets/6563893/16713715/714127ba-46b0-11e6-9de9-43bab7708254.PNG)

**Comment by homerofgods** [comment]
How to reproduce:
Turn ON Show Grid
Close PW
Open PW
You should now see Greed option as off.

*you cannot reproduce the other way (turning off grid and reopen) because Grid option will show as off no matter what.

It should not be that hard to reproduce so maybe something you did fixed this too. Well see when the update comes. I also have Win10 64' Pro. 
My PW is installed in a folder within Soldat directory

**Comment by ExHunter** [comment]
Reopened. Will try to reproduce and fix it (if it happens how you described it)

**Comment by Shoozza** [comment]
Done
