### ISSUE TITLE
Set license for applied patches

### ISSUE THREAD

**Issue by Shoozza** [Soldat/polyworks#8]
@ExHunter and @Fryer could you please tell me if you are fine if we use MIT license for all patches applied to the original Polyworks Source?

**Comment by Fryer** [comment]
Fine with me 👌

**Comment by ExHunter** [comment]
Sorry I was gone for too long. If it is still relevant, definately fine by me aswell.

**Comment by Shoozza** [comment]
Btw the installer was written with help from Zakath. We need him to agree on the MIT License for his contribution as well.

**Comment by tonylibell** [comment]
Its fine with me

**Comment by Shoozza** [comment]
> Its fine with me

Thanks Zakath 👍
