### ISSUE TITLE
NSIS script is broken

### ISSUE THREAD

**Issue by brakeflash** [Soldat/polyworks#9]
the NSIS script is broken so I cant install Polyworks

log:
MakeNSIS v3.05 - Copyright 1999-2019 Contributors
See the file COPYING for license details.
Credits can be found in the Users Manual.

Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
Processing default plugins: "C:\Program Files (x86)\NSIS\Plugins\x86-ansi\*.dll"
 + Banner::destroy
 + Banner::getWindow
 + Banner::show
 + BgImage::AddImage
 + BgImage::AddText
 + BgImage::Clear
 + BgImage::Destroy
 + BgImage::Redraw
 + BgImage::SetBg
 + BgImage::SetReturn
 + BgImage::Sound
 + Dialer::AttemptConnect
 + Dialer::AutodialHangup
 + Dialer::AutodialOnline
 + Dialer::AutodialUnattended
 + Dialer::GetConnectedState
 + InstallOptions::dialog
 + InstallOptions::initDialog
 + InstallOptions::show
 + LangDLL::LangDialog
 + Math::Script
 + StartMenu::Init
 + StartMenu::Select
 + StartMenu::Show
 + System::Alloc
 + System::Call
 + System::Copy
 + System::Free
 + System::Get
 + System::Int64Op
 + System::Store
 + System::StrAlloc
 + TypeLib::GetLibVersion
 + TypeLib::Register
 + TypeLib::UnRegister
 + UserInfo::GetAccountType
 + UserInfo::GetName
 + UserInfo::GetOriginalAccountType
 + VPatch::GetFileCRC32
 + VPatch::GetFileMD5
 + VPatch::vpatchfile
 + advsplash::show
 + nsDialogs::Create
 + nsDialogs::CreateControl
 + nsDialogs::CreateItem
 + nsDialogs::CreateTimer
 + nsDialogs::GetUserData
 + nsDialogs::KillTimer
 + nsDialogs::OnBack
 + nsDialogs::OnChange
 + nsDialogs::OnClick
 + nsDialogs::OnNotify
 + nsDialogs::SelectFileDialog
 + nsDialogs::SelectFolderDialog
 + nsDialogs::SetRTL
 + nsDialogs::SetUserData
 + nsDialogs::Show
 + nsExec::Exec
 + nsExec::ExecToLog
 + nsExec::ExecToStack
 + nsisdl::download
 + nsisdl::download_quiet
 + splash::show

!define: "MUI_INSERT_NSISCONF"=""

Changing directory to: "C:\Users\kruse\Downloads\polyworks-develop\pwinstall"

Processing script file: "C:\Users\kruse\Downloads\polyworks-develop\pwinstall\pw.nsi" (ACP)
!define: "PRODUCT_NAME"="Soldat PolyWorks"
!define: "PRODUCT_VERSION"="1.5.0.13"
!define: "PRODUCT_PUBLISHER"="Copyright Anna Zajaczkowski"
!define: "PRODUCT_WEB_SITE"="http://forums.soldat.pl"
!define: "PRODUCT_DIR_REGKEY"="Software\Microsoft\Windows\CurrentVersion\App Paths\Soldat PolyWorks.exe"
!define: "PRODUCT_UNINST_KEY"="Software\Microsoft\Windows\CurrentVersion\Uninstall\Soldat PolyWorks"
!define: "PRODUCT_UNINST_ROOT_KEY"="HKLM"
!include: "C:\Program Files (x86)\NSIS\Include\MUI.nsh" (ACP)
!include: "C:\Program Files (x86)\NSIS\Contrib\Modern UI\System.nsh" (ACP)
NSIS Modern User Interface version 1.81 - Copyright 2002-2019 Joost Verburg (C:\Program Files (x86)\NSIS\Contrib\Modern UI\System.nsh:13)
!include: closed: "C:\Program Files (x86)\NSIS\Contrib\Modern UI\System.nsh"
!include: closed: "C:\Program Files (x86)\NSIS\Include\MUI.nsh"
!define: "MUI_ABORTWARNING"=""
!define: "MUI_ICON"="PW.ico"
!define: "MUI_UNICON"="PW.ico"
!insertmacro: MUI_PAGE_WELCOME
!insertmacro: end of MUI_PAGE_WELCOME
!insertmacro: MUI_PAGE_LICENSE
!insertmacro: end of MUI_PAGE_LICENSE
!insertmacro: MUI_PAGE_DIRECTORY
!insertmacro: end of MUI_PAGE_DIRECTORY
!insertmacro: MUI_PAGE_INSTFILES
!insertmacro: end of MUI_PAGE_INSTFILES
!insertmacro: MUI_PAGE_FINISH
!insertmacro: end of MUI_PAGE_FINISH
!insertmacro: MUI_UNPAGE_INSTFILES
!insertmacro: end of MUI_UNPAGE_INSTFILES
!insertmacro: MUI_LANGUAGE
!insertmacro: end of MUI_LANGUAGE
!define: "SHCNE_ASSOCCHANGED"="0x8000000"
!define: "SHCNF_IDLIST"="0"
Name: "Soldat PolyWorks 1.5.0.13"
OutFile: "PWSetup.exe"
InstallDir: "$PROGRAMFILES\Soldat PolyWorks"
InstallRegKey: "HKLM\Software\Microsoft\Windows\CurrentVersion\App Paths\Soldat PolyWorks.exe\"
ShowInstDetails: show
ShowUnInstDetails: show
Section: "MainSection" ->(SEC01)
SetOutPath: "$INSTDIR"
SetOverwrite: ifnewer
File: "Soldat PolyWorks.exe" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "C:\Users\kruse\Downloads\polyworks-develop\pwinstall\pw.nsi" on line 55 -- aborting creation process

Please help!!

**Comment by Shoozza** [comment]
By any chance, could it be that your antivirus is deleting the file or otherwise restricting access to the "Soldat PolyWorks.exe" file?
Maybe disabling it would allow you to install PolyWorks?
